### ISSUE TITLE
some error occurs when do the footskating clean

### ISSUE THREAD

**Issue by wangsen1312** [h-y1heng/StableMoFusion#1]
The error shows below:

![error_footskate](https://github.com/h-y1heng/StableMoFusion/assets/11545246/f8262960-623a-4fdc-92d7-e2a27a0e0c30)

**Comment by h-y1heng** [comment]
The problem seems to be due to the dataset folders under UnderPressure having no data or not being organized in the structure they require (https://github.com/InterDigitalInc/UnderPressure/tree/main/dataset#readme):
![微信图片_20240517143221](https://github.com/h-y1heng/StableMoFusion/assets/100835198/9bb6fd17-9cba-4e3b-bb62-f6348cc5ac0e)
![屏幕截图 2024-05-17 143049](https://github.com/h-y1heng/StableMoFusion/assets/100835198/a9a36ac6-b9b9-4ae0-b5ec-d769921c5197)

So the skeleton data read by the code `Skeletons.all()[0]` is an empty list.

**Comment by wangsen1312** [comment]
The problem has been solved.

**Comment by h-y1heng** [comment]
**Update**. To make this issue easier, we've updated the code `scripts/train_UnderPressure_model.py` and `utils/footskate_clean.py`, and provided a processed UnderPressure skeleton data in `./UnderPressure/dataset/S1_HoppingLeftFootRightFoot.pth`.  In this way, you can run our scripts without loading and process the dataset in UnderPressure.
